root: true
env:
  browser: true
  node: true
  es6: true
  jquery: true
extends:
  - google
  - jquery
  - prettier
parserOptions:
  sourceType: module
  ecmaVersion: 2017
rules:
  no-invalid-this: false
ignorePatterns:
  - '/**/node_modules/**'
  - '/htdocs'
  - 'babel.config.js'
  - 'bs-config.js'
  - 'postcss.config.js'
  - 'webpack.config.js'
