printWidth: 120 # 折り返す行の長さを指定(80)
tabWidth: 2 # インデントのスペースの数を指定(2)
useTabs: false # スペースではなくタブで行をインデントする(false)
semi: true # ステートメントの最後にセミコロンを追加(true)
singleQuote: true # ダブルクォートの代わりにシングルクォートを使用(false)
quoteProps: 'as-needed' # オブジェクトのプロパティが引用されるときに変更(as-needed)
jsxSingleQuote: false # JSXでダブルクォートの代わりにシングルクォートを使用(false)
trailingComma: 'es5' # 末尾のカンマの設定(es5)
bracketSpacing: true # オブジェクトリテラルの角かっこの内側にスペースを入れる(true)
bracketSameLine: false # 複数行のJSX要素の最終行の最後に「>」を置く(false)
arrowParens: 'always' # アロー関数の()が省略可能でも常に書く(always)
requirePragma: false # ファイルの一部のセグメントのみフォーマットさせます。(false)
insertPragma: false # ファイルの先頭にプラグマ(/** @format */)を挿入する(false)
proseWrap: 'preserve' # markdownの折返しの設定(preserve)
htmlWhitespaceSensitivity: 'css' # HTMLファイルのグローバルな空白の感度を指定(css)
vueIndentScriptAndStyle: false # Vueファイル内の<script>と<style>をインデントするかどうかの指定(false)
endOfLine: 'lf' # 改行の文字コードを指定(lf)
