extends:
  - stylelint-config-standard
  - stylelint-config-standard-scss
  - stylelint-config-recess-order
  - stylelint-config-prettier
  - stylelint-prettier/recommended
plugins:
  - stylelint-scss
syntax:
  - scss
rules:
  prettier/prettier: [true, { singleQuote: true }]
  at-rule-no-unknown: null
  scss/dollar-variable-colon-space-before: never
  scss/operator-no-unspaced: true
  scss/at-rule-no-unknown: true
  selector-class-pattern: null
  at-rule-allowed-list:
    [
      'extend',
      'keyframes',
      'import',
      'include',
      'charset',
      'font-face',
      'content',
      'mixin',
      'if',
      'else',
      'media',
      'for',
      'at-root',
      'supports',
      'function',
      'return',
      'warn',
      'get-color',
      'scale-color',
      'each',
      'use',
      'forward',
      'error',
    ]
  comment-empty-line-before: null
  function-no-unknown: [true, { ignoreFunctions: ['math.div', 'pxtovw', 'pxtorem', 'color.scale'] }]
  media-feature-name-no-unknown: [true, { ignoreMediaFeatureNames: ['min-device-pixel-ratio'] }]
  font-family-no-missing-generic-family-keyword: [true, { ignoreFontFamilies: ['icons', 'FontAwesome'] }]
ignoreFiles:
  - node_modules/**
  - htdocs/**/*.css
  - htdocs/**/fonts/**
  - htdocs/**/images/**
  - htdocs/**/img/**
  - tmp/**
